### ISSUE TITLE
HTML in Measure Labels

### ISSUE THREAD

**Issue by flrs** [flrs/visavail#11]
In issue #10, ijunaid8088 posted:

> 
> Hi Thanks for all your efforts..
> 
> Actually my issue was:I want to add an fa-icon with measure string, such as if
> 
> `"measure <i class='fa fa-icon'></i>"`
> 
> Something like this could be possible?

This issue addresses this request.

**Comment by flrs** [comment]
Fixed in referenced commit. Use like this:

```javascript
var dataset = [{
    "measure_html": "<span title='Price of security at end of day'>&#x1F6AA; Closing Price</span>", // HTML code
    "interval_s": 365 * 24 * 60 * 60,
    "data": [
        ["2015-01-01", 0], 
        ["2016-01-01", 1],
        ["2017-01-01", 1],
        ["2018-01-01", 1]
    ]
}];
```

I have uploaded [an example for you](https://github.com/flrs/visavail/blob/master/examples/example_html_labels.htm).

**Comment by ijunaid8989** [comment]
Thanks a lot @flrs
