### ISSUE TITLE
Feature Question/Suggestion

### ISSUE THREAD

**Issue by JohnOmernik** [flrs/visavail#13]
Hello, I was looking around and found your project as an almost perfect example of the visualization I need for a project of mine.  I had a few questions, that I am sure, if/when I learn Javascript a bit better may be answerable by me, but as of now (and I still plan on diving in, I am just asking the question as I am sure others can answer this fairly easily)  I don't see the answer.  I am not a strong web/java script programmer, but I know python fairly well, so I will look up stuff (I am not a total programming novice, just in the web front end stuff)  Any help on any of these questions is appreciated!

1. Control of the "Y Axis" labels. (on the home page of this repo, I would consider Y axis label to be the "Balance Sheet", "Closing Price" etc.  What I mean by this is the ability to do a tool tip hover for more information, make the text links, or even do a hide/show for more information that would just extend the whole graph to make room of additional text etc. 

2. Changing of the "Date" labels to be another form of time.  For example, what I just wanted to use HH:MM:SS on a single day, and only show the time?  from 00:00:00 to 00:00:05 or 00:00:10 to 00:12:03 as my time chunks, completely ignoring the date? I could probable pick the same date for each one to hack my way in, but I'd want to label to only show the time... etc.  Thoughts?

3. Links or tool tips, or divs that open for each chunk of time. Right now there is a change of hover over, but I'd love to see the ability to shove information into those as needed. 

This project looks outstanding, and I appreciate the work that has gone into it. As I play with it, I will be happy to contribute back anything that I add or tweak as options. 

Thanks for your hard work!

**Comment by flrs** [comment]
Hi @JohnOmernik, sorry it took so long to get to this request. I am glad that you are thinking about using the visualization for your own project. Please find my comments regarding your points below.

1. There is a way to put HTML into the Y axis label, see issue #11. This might help you to get (some) of the desired flexibility.

2. Issue #16 calls for customization of the X axis labels. I posted a couple of links in my answer that dive a little deeper into how to format the labels in a custom way.

3. I have looked at tool tips before and know that it is possible. Adding information to the individual time intervals would definitely be an interesting feature!

Let me know if any of that helps at all or if you have come up with any other improvements.

**Comment by tanganellilore** [comment]
Hi @JohnOmernik ,

I close this issue becasue new visavail library have all requested enhancement.

1) you can use new tooltip function 
2) you can use custom format object
3)you have the possibility to use two different tooltip with adding of some description (see doc file)

Enjoy with new visavail library!
