### ISSUE TITLE
Is there any function to reduce the height of visavail status bar.

### ISSUE THREAD

**Issue by affan00** [flrs/visavail#14]
I want to reduce the height of the visavail chart. 
![image](https://user-images.githubusercontent.com/14149453/27788415-f44968d2-6001-11e7-9cde-cf2b8676bb8a.png)

Can we change the fonts on it so that it is easier to read. (e.g. Bold for Days, smaller for hours) ?

**Comment by flrs** [comment]
Hi @affan00!

1. There are several elements you can adjust to reduce the height of the chart:
- [Top margin](https://github.com/flrs/visavail/blob/master/visavail/js/visavail.js#L5)
- [Bottom margin](https://github.com/flrs/visavail/blob/master/visavail/js/visavail.js#L10)
- [Height of horizontal data bars](https://github.com/flrs/visavail/blob/master/visavail/js/visavail.js#L17)
- [Spacing between horizontal data bars](https://github.com/flrs/visavail/blob/master/visavail/js/visavail.js#L20)
- [Vertical space for heading](https://github.com/flrs/visavail/blob/master/visavail/js/visavail.js#L23)

2. In the existing code, there is a way to modify year ticks to be bold. Have a look at the [this code](https://github.com/flrs/visavail/blob/master/visavail/js/visavail.js#L424):
```javascript
      var xTicks = xScale.ticks();
      var isYearTick = xTicks.map(isYear);
      var isMonthTick = xTicks.map(isMonth);
      // year emphasis
      // ensure year emphasis is only active if years are the biggest clustering unit
      if (emphasizeYearTicks
          && !(isYearTick.every(function (d) { return d === true; }))
          && isMonthTick.every(function (d) { return d === true; })) {
        d3.selectAll('g.tick').each(function (d, i) {
          if (isYearTick[i]) {
            d3.select(this)
                .attr({
                  'class': 'x_tick_emph',
                });
          }
        });
        d3.selectAll('.vert_grid').each(function (d, i) {
          if (isYearTick[i]) {
            d3.select(this)
                .attr({
                  'class': 'vert_grid_emph',
                });
          }
        });
      }
```
You would have to modify that to emphasize whatever interval you want to highlight.

I hope this helps you to reach your goal!
