### ISSUE TITLE
getting d.getFullYear is not a function error when no data is there in the dataset

### ISSUE THREAD

**Issue by snsnanda** [flrs/visavail#20]
Hi, 
I am using Visavail chart to show dataset based on datetime.
When I do not have any data in dataset, then while launching the chart it is throwing an error i.e.  d.getFullYear is not a function.
How can I handle this error?

Thanks & Regards,
Shitikantha Nanda

**Comment by flrs** [comment]
Hey @snsnanda, I just fixed this error. Let me know if you still get any errors.
