### ISSUE TITLE
time scale is not using moment.locale()

### ISSUE THREAD

**Issue by adas172002** [flrs/visavail#21]
Hi,

I am trying to make a localized axis labels to present month names and time/date format of choice given by `moment.locale()`. I see that some parts of chart (tooltips, subtitle) pick up locale set in `moment`, however time scale seems to be hard - coded to US locale. I am not sure if this is related to d3.time.scale or other part of `visavail.js`. Can you suggest a solution to my issue?

**Comment by tanganellilore** [comment]
Hi @adas172002 ,

now the library go to v 2.0 and moment it integrate with locale function.

Enjoy with visavail 2.0
