### ISSUE TITLE
How to change height of bars

### ISSUE THREAD

**Issue by FunDeckHermit** [flrs/visavail#23]
What parameters do I need to edit to change the height of the bars?

**Comment by flrs** [comment]
Hi @mindfuucker, you can change the height of the bars through changing the variable `dataHeight` in visavail.js, see here: https://github.com/flrs/visavail/blob/99e793767ac12b0491fcf799b8d4ced8b96f7dc0/visavail/js/visavail.js#L17

**Comment by FunDeckHermit** [comment]
Thank you!
