### ISSUE TITLE
Change structure of library for enhancement functionality

### ISSUE THREAD

**Issue by tanganellilore** [flrs/visavail#25]
Hi @flrs ,

I see your library and I think is a good base for create interactive graph similar to hmi for industrial.

I use it in some project and I developed a new version with some enhancement:

-  I introduced an external configuration for a usefull adn flexible personalizzation (with this options we can modify the library without change the code of the library)

-  I upgraded the version of d3.js used to 4.13.0 (in the next days I will update to v.5)

-  I introduce in the option possibility to integrate locale configuration for custom xAxis label ( at this moment the configuration is static but I want to became semi-automatico with only insert the language as same d3-time-format)

- Adding support for customize the laber on the graph

-  I delete some lines of code with adding a lot of options in the configuration (some check aren't unecessary)

If you are interesting to develop togheter a new version with some enhancement I'm avilable to check and merge my version with your version.

You can see the change in the fork of your library into my account.

Thanks a lot 
Lorenzo

**Comment by flrs** [comment]
Hi @tanganellilore,

I looked at your code -- thank you, this looks like a great improvement! The d3.js upgrade was long overdue and the external configuration is highly appreciated!

We should merge your improvements into this project. Let me know when you think it is ready to be merged (you said you still wanted to make some changes). Also, it would be nice if you could test as much as you can. I will also do a separate test before merging.

Thanks!
Florian

**Comment by flrs** [comment]
Also, localization has been a big problem in the past ( #21 #24 ). If you find a way to make it semi-automated as described above this will really have a relevant impact!

**Comment by tanganellilore** [comment]
Hi @flrs,
I explain all tasks in the follow list:

- [x] Implement configuration options (json format)
- [x] Upgrade to d3 v4.13
- [x] Ugrade to d3 v.5.2
- [x] Implement new moment logical for custom locale
- [x] Possibility to take responsive more efficently  and without jQuery
- [x] Modify all example with new implementation
- [x] Modify documentation for new configuration

For the moment there it's all.

Please follow the check list for control the completed task

Thanks Lorenzo

**Comment by flrs** [comment]
Thanks, I will follow up on this. It might take a week or two.

**Comment by tanganellilore** [comment]
Hi @flrs,

I close some enhancement posted before.
Now the graph work with d3.js v4 and v5 and I adjust some problem with the date format and the multilanguage graph date (i use moment) 

Now I'm dedicate to implement new function for zomming the chart with the timeline. 

I implement a base of zomming but i need some time to test it in some scenario and integrate with the new function for responsive layout. 
At the moment there is a little bug in the Responsive chart with the x-axis, date format and ticks (when the page is small the x ticks and x label overlap) 

Thanks 
Lorenzo

**Comment by flrs** [comment]
Wow, that sounds like good progress! Keep it up and thanks again!

**Comment by tanganellilore** [comment]
Hi @flrs ,
I'm not forgot you!!!
I does some enhancement into Visavail from last my comment. 
The principal news are:

1. Implement function for zooming 
2. Implement function for responsive
3. Implement function for wrap the ytitle
4. Implement moment.locale
5. Rewrite the structure of plugin for import into another language (ex. angular)
6. Implement new functionality for custom the graph with a JSON Options
7. Implement new function for destroy, redraw, update, display range the graph
8. Implement new type of tooltip ("overlay" => follow the mouse pointer)
9. Implement new type of bar ("rhombus" => create some rhombs instead of bar)

I tested it in some browser ( Chrome, Firefox, IE, Edge) but at the moment I not have time to rewrite the documentation and the html examples of new library.

Can You help me???

**Comment by flrs** [comment]
Hi @tanganellilore,

This is awesome, I am super excited to try the new features. I gladly provide documentation and examples. Give me about four weeks or so and then I can start pulling this together.

Thank you so much for your help!

**Comment by tanganellilore** [comment]
@flrs I think in the next day I work in visavail for adjust the tick on resize graph (when the graph is small) and I want to create one Big example for help you to understand the new functionality.

Stay tuned

**Comment by tanganellilore** [comment]
@flrs  i update visavail in my fork. I delete some file and adding folder "docs" with some example of new functionality.
I fixed the library in some scenario (i correct some bugs)

**Comment by petertkim** [comment]
@tanganellilore @flrs Hello,

I am running into this error when I use your enhancement:

     Uncaught TypeError: d3.timeFormatDefaultLocale is not a function

within 'function chart(selection)' on this line:

     //set to locale with moment
     d3.timeFormatDefaultLocale(options.locale);

Is this because the 'd3' from 'vendors' is an old version?  Please advise.

**Comment by tanganellilore** [comment]
Hi @petertkim,

my version use d3.js v5.5.0 (the latest version).
The Original version of visavail use an old version of d3.
For supporting moment locale and another functionality (zoom for example) we need the new version of d3.js.

In my fork you find the new library and new example for use the new library.
For some enhancement I rewrote some part of the library and the settings are some different.

Please if you use my fork follow the new example under folder "docs"
If you use the visavail origil github use the instruction in readme

Good day

**Comment by petertkim** [comment]
Hi @tanganellilore , thanks for responding above.

Additionally, for some reason when I use your enhancement it shifts my data's time range up by 6 hours.  Here is a screenshot of the difference.  Why is this?  And is there a way to fix this?  Thanks.

Original:
![image](https://user-images.githubusercontent.com/35403143/43096675-7837dfdc-8e7f-11e8-981d-a62321f3662a.png)

New:
![image](https://user-images.githubusercontent.com/35403143/43096698-846e7090-8e7f-11e8-8e70-b67d73b98494.png)

**Comment by tanganellilore** [comment]
I can't help you without posting or publishing your code.
I think there is an error in your setting with moment and your browser ( in the latest version I adding the options if data in dataset are in UTC format or not )

**Comment by petertkim** [comment]
Hi @tanganellilore ,

This is how I set my dataset's time:

     dataset = []
      //for (var arr in activeStates)
      for (var i=0; i<activeStates.length; i++)
      {
        var arr = activeStates[i];

        // for (var e in arr)
        // {
        //   console.log(e);
        // }
        device_name = arr[0].substr(0,arr[0].indexOf(' ')); // e.g. Roomba_880
        device_action = arr[0].substr(arr[0].indexOf(' ')+1); // e.g. charge

        console.log('device_name: ', device_name, 'device_action: ', device_action);

        color = "purple"
        switch(device_action)
        {
          case "wash":
            color = "Aqua"; //"#00ffff";
            break;
          case "regular":
            color = "Beige"; //"#f5f5dc"; 
            break;
          case "heat":
            color = "Crimson"; //"#dc143c"; 
            break;
          case "charge_48a":
            color = "GoldenRod"; //"#daa520"; 
            break;
          case "bake":
            color = "FireBrick"; //"#b22222"; 
            break;
          case "broil":
            color = "Red"; //"#ff0000"; 
            break;
          case "vacuum":
            color = "SpringGreen"; //"#00ff7f"; 
            break;
          case "charge":
            color = "Yellow"; //"#ffff00";
            break;
        }
        categories = {
          [device_action]: { "color": color} // [var] uses the actual value of the variable, var as the json key.
        }

        data = []
        for (var j=1; j<arr.length; j++) // skip arr[0]="deviceName action"
        {
          if (arr[j] == 1)
          {
            start_time = ""
            end_time = ""
            // HARD CODED FOR NOW.
            switch(j)
            {
              case 1:
                start_time = "2016-01-01 00:00:00";
                end_time = "2016-01-01 02:00:00";
                break;
              case 2:
                start_time = "2016-01-01 02:00:00";
                end_time = "2016-01-01 04:00:00";
                break;
              case 3:
                start_time = "2016-01-01 04:00:00";
                end_time = "2016-01-01 06:00:00";
                break;
              case 4:
                start_time = "2016-01-01 06:00:00";
                end_time = "2016-01-01 08:00:00";
                break;
              case 5:
                start_time = "2016-01-01 08:00:00";
                end_time = "2016-01-01 10:00:00";
                break;
              case 6:
                start_time = "2016-01-01 10:00:00";
                end_time = "2016-01-01 12:00:00";
                break;
              case 7:
                start_time = "2016-01-01 12:00:00";
                end_time = "2016-01-01 14:00:00";
                break;
              case 8:
                start_time = "2016-01-01 14:00:00";
                end_time = "2016-01-01 16:00:00";
                break;
              case 9:
                start_time = "2016-01-01 16:00:00";
                end_time = "2016-01-01 18:00:00";
                break;
              case 10:
                start_time = "2016-01-01 18:00:00";
                end_time = "2016-01-01 20:00:00";
                break;
              case 11:
                start_time = "2016-01-01 20:00:00";
                end_time = "2016-01-01 22:00:00";
                break;
              case 12:
                start_time = "2016-01-01 22:00:00";
                end_time = "2016-01-01 23:59:59";
                break;
            }
            data.push([start_time, device_action, end_time]);
          }
        }

        device_visavail = {
          "measure": device_name,
          "categories": categories,
          "data": data
        }
        dataset.push(device_visavail)
      }

**Comment by tanganellilore** [comment]
In the option configuration there is a parameter "date_in_utc". Default is true (I suppose the data savede ave the UTC time) but if your data are already converted in local timezone you can set the date_in_utc at false and the library not covert the time.

I use moment for parse the data then ATTENTION for the time of your chart (moment convert the time in the current timezone of the browser )

see [example with option "date_in_utc"](https://jsfiddle.net/sb35rafm/13/)

**Comment by petertkim** [comment]
Thank you very much @tanganellilore !

**Comment by tanganellilore** [comment]
hi @flrs,

I found soime time for create new example and new docs.

I use github page for the new library.
You can find all in my fork.
If you want merge my work with your I ask you if I can became a developer in this repository.

Thanks

Lorenzo

**Comment by flrs** [comment]
Hi @tanganellilore,

Thank you so much for pulling all of this together. You did a great service to the community and this library! I gladly merge your fork in the next couple of weeks.

Florian

**Comment by otabekgb** [comment]
@tanganellilore, thanks for your work. We should add following ie11 polyfil in your visavail.js

Number.isInteger = Number.isInteger || function(value) {
    return typeof value === "number" && 
           isFinite(value) && 
           Math.floor(value) === value;
};

**Comment by tanganellilore** [comment]
Sorry @otabekgb but I don't understand your request.

Wich type of problem do you have with ie11?

**Comment by otabekgb** [comment]
also  to prevent chart overflow bug we should change follwoing method:
function widthForPoint(d, xScale){
					
					var x_scale_d0 = xScale(d[0]);
					var x_scale_d2 = xScale(d[2]);
					
					if(options.date_is_descending) {
						x_scale_d0 = xScale(d[2]);
						x_scale_d2 =  xScale(d[0]);
					}
					
					if((!options.date_is_descending && (x_scale_d2 - x_scale_d0) < 0) || x_scale_d2 < 0 && x_scale_d0 < 0)
						return 0;
					if(options.date_is_descending && (x_scale_d2 - x_scale_d0) < 0)
						return (-1*(x_scale_d2 - x_scale_d0))
					if(options.graph.type == "rhombus" || options.graph.type == "circle" ){
						if(x_scale_d0 < 0)
							return 0
						return options.graph.width;
					}

					if (x_scale_d0 < 0 && x_scale_d2 > 0)
						return x_scale_d2
					if (x_scale_d2 < 0 && x_scale_d0 > 0)
                        return x_scale_d0
                    var chartWidth = options.width - options.margin.left - options.margin.right;
                    return (x_scale_d2 > chartWidth ? chartWidth : x_scale_d2) - x_scale_d0;
				}

**Comment by otabekgb** [comment]
> Wich type of problem do you have with ie11?
on ie11 Number.isInteger is not defined, so we should define at top

**Comment by tanganellilore** [comment]
@otabekgb for ie11 bugs in my repository I update with your function.

For widthForPoint(d, xScale) which type of bug do you referr.
My code with widthForPoint it's different comapre to your shared code.

Please if you find any type of bugs open a iusse in my repo because this repo it's not update adn also if you can explain with more detail your problem (with image for example) it's better for a quick resolution

Thanks

**Comment by otabekgb** [comment]
There is no issue tracking enabled on your rep. If I set a time range to chart, some status rectangles overflowing at the end of chart, start is fine. 
`var chartWidth = options.width - options.margin.left - options.margin.right;
return (x_scale_d2 > chartWidth ? chartWidth : x_scale_d2) - x_scale_d0;`
this fixes it. Before it was:
`return (x_scale_d2 - x_scale_d0);`

**Comment by tanganellilore** [comment]
Hi, now you can open a issue in my repo.

This issue is close and for bug fixing open one on my repo. 

If you open a iusse in my repo.... Please attach some picture for identify the problem
Thanks

**Comment by tanganellilore** [comment]
> There is no issue tracking enabled on your rep. If I set a time range to chart, some status rectangles overflowing at the end of chart, start is fine.
> `var chartWidth = options.width - options.margin.left - options.margin.right; return (x_scale_d2 > chartWidth ? chartWidth : x_scale_d2) - x_scale_d0;`
> this fixes it. Before it was:
> `return (x_scale_d2 - x_scale_d0);`

@otabekgb  I changed little bit the function for draw the width of rectangle. 
I don't understand clear the bug that you find but Now the drawing is more precise (the ending of rectangle in the right of the chart not exceed).

Please for other problem/question open a issue in my rep.
Thanks
