### ISSUE TITLE
Chart Data Overlaps with Axis Labels

### ISSUE THREAD

**Issue by petertkim** [flrs/visavail#26]
Hello All,

I have an issue where the data of the chart overlaps with the axis labels on the left side, because my measure labels (names of smart devices) often end up being quite long.  There is also a weird blue background/vertical bar and I cannot figure out where it is coming from.

I appreciate any help! Thanks in advance!

Best,

Peter Kim
<img width="967" alt="visavail_schedule" src="https://user-images.githubusercontent.com/35403143/42536986-4669f3a8-8459-11e8-85da-36b52b4345e3.png">

**Comment by flrs** [comment]
Hi @petertkim,

You can change the space on the left here: https://github.com/flrs/visavail/blob/99e793767ac12b0491fcf799b8d4ced8b96f7dc0/visavail/js/visavail.js#L13

As to the blue color I do not have an answer. Can you post your code?

Florian

**Comment by petertkim** [comment]
Thank you Florian!

I realized the blue color was something I set as a < p > style way back when... Silly me to forget.

Thanks so much!

Peter

**Comment by flrs** [comment]
Great that you figured that blue background thing out!
The plot title is set here:

https://github.com/flrs/visavail/blob/99e793767ac12b0491fcf799b8d4ced8b96f7dc0/visavail/js/visavail.js#L460

Florian
