### ISSUE TITLE
Chart doesn't display title on Internet Explorer.

### ISSUE THREAD

**Issue by affan00** [flrs/visavail#27]
I am using visavail chart to display online/offline status reports of cameras, but it doesn't display camera name on Internet Explorer browser, It's working fine on chrome.
Thank you in advance. 

Result on IE:
![visavail_ie_bug](https://user-images.githubusercontent.com/14149453/42567886-b235faac-8524-11e8-8a15-dcb9e41dfc30.jpg)

Result on Chrome:
![screenshot from 2018-07-11 16-10-23](https://user-images.githubusercontent.com/14149453/42567978-f87e0c70-8524-11e8-9264-d85d9eb8ed22.png)

**Comment by flrs** [comment]
That's interesting. Can you see the titles in Internet Explorer in this example? (I can.) http://phatduino.com.w010a51b.kasserver.com/visavail/example.htm

**Comment by affan00** [comment]
Yes, I can.

**Comment by flrs** [comment]
Could you post the code of the page so we can have a look?

**Comment by affan00** [comment]
Yes sure, 
You can see the related code in this zip file. thanks :)
[visavail chart code.zip](https://github.com/flrs/visavail/files/2191482/visavail.chart.code.zip)

**Comment by affan00** [comment]
Any update?

**Comment by affan00** [comment]
??

**Comment by flrs** [comment]
I'll have a look at it within the next 12 hours.

**Comment by flrs** [comment]
Hi @affan00,

Unfortunately I have no way to test your code on IE at the moment, but I do have a suspicion. If you look at line 228 of your code of visavail.js it says
```javascript
      labels.append('foreignObject') // This is line 228
        .attr('x', paddingLeft)
        .attr('y', lineSpacing + dataHeight / 2)
// and so on...
```
The corresponding line of the current code shows: https://github.com/flrs/visavail/blob/99e793767ac12b0491fcf799b8d4ced8b96f7dc0/visavail/js/visavail.js#L241

It looks as if in your code the `text` was replaced with `foreignObject`. According to [MSDN](https://msdn.microsoft.com/en-us/library/hh834675%28v=vs.85%29.aspx), `foreignObject` is not supported by IE11 and below.

I hope this helps!

**Comment by affan00** [comment]
Thanks, @flrs 
That fixed the issue. :+1:
