### ISSUE TITLE
ToolTips

### ISSUE THREAD

**Issue by FrolicBrain** [flrs/visavail#29]
When I pass the data's with date and time.The tool tip is showing one hour extra from the given value

Ex:If I gave '03:00:00' it showing ''04:00:00";

what should i want to do?

**Comment by tanganellilore** [comment]
Can you provider with some example/screenshot or link???

I create a branch of this Library with some enhancment, you can sere #25.
Is a new version of visavail with new options and Support of moment.

**Comment by FrolicBrain** [comment]
Ok sir.Did i want to update by visavail? and can you send the link

![chart](https://user-images.githubusercontent.com/44859078/48183697-9c5f0b80-e355-11e8-8a50-c80db0f5c805.jpg)

**Comment by tanganellilore** [comment]
You can follow #25 for the fork.

In your case without code we can't help you.
Only things, you use define block or any option for set a size of block?

If you try the example in visavail folder you have this iusse??

**Comment by tanganellilore** [comment]
Hi @FrolicBrain,

now my fork is merged with this official repo.
This bug is fixed.
