### ISSUE TITLE
Dataset hours, minutes & seconds

### ISSUE THREAD

**Issue by piemasters** [flrs/visavail#3]
I wanted to say this library looks great and almost perfect for my needs. 

The only thing I need is the ability to post events that are hours/minutes/seconds long. I was wondering if it was possible to do this, as I see you can set interval? I'm thinking something like this:

"data": [
        ["2016-01-01 12:00:00", 1, "2016-01-01 13:00:00"],
        ["2016-01-01 14:22:51", 1, "2016-01-01 16:14:12"],
        ["2016-01-01 08:30:00", 1, "2016-01-01 09:00:00"]
]

Thanks and again great job!

**Comment by flrs** [comment]
Hi @piemasters, I am glad that you like the library and you are interested in using it. Thanks!
I think that being able to use times and not only dates would be a great addition. I will look into this and keep you updated here.

**Comment by flrs** [comment]
Hey @piemasters, I just implemented the feature you requested. Check out the example at [https://github.com/flrs/visavail/blob/master/examples/example_dates_and_times.htm](https://github.com/flrs/visavail/blob/master/examples/example_dates_and_times.htm).

**Comment by piemasters** [comment]
This is perfect thank you so much! :)
