### ISSUE TITLE
X axis backwards viewing

### ISSUE THREAD

**Issue by deesethu** [flrs/visavail#31]
I want to be able to view data in such a way that the most recent appears first. 
Currently the chart is built from start date to end date. can we build the same chart starting from the end date..
In detail - 
http://phatduino.com.w010a51b.kasserver.com/visavail/example.htm
In the above example, the Data Availability plot is from June 2014 to Jan 2019. Can we display the same in descending order. i.e. Jan 2019 ... 2018 .. 2017 ... June 2014?

@flrs can you help with this..

**Comment by tanganellilore** [comment]
Hi @deesethu ,

I have adding in my fork this type of request.
At the moment the lib take the normal dataset (in ascending order) and view in descending order.

Sorry but at the moment I haven't time to rework all parsing for take the dataset in descending order and recreate graph, but I think this is the correct solution for a timeline graph ( dataset in ascending order and possibility to see this in ascendig view or descending view)

If there are little bug or other please open an issue in my fork.
Thanks

**Comment by tanganellilore** [comment]
Hi @deesethu 

now my fork is merged with this package.
The descending timeline is reday.

Enjoy with visavail 2.0
