### ISSUE TITLE
Zoom Function

### ISSUE THREAD

**Issue by Chatcola** [flrs/visavail#34]
Hi, I already love this and I'm replacing old js charts.
I heard about a Zoom function on the issues.
Is it possible to zoom on charts like this project ( https://github.com/vasturiano/timelines-chart ) ?
Thanks by advance.

**Comment by tanganellilore** [comment]
Hi @Chatcola,

in this library at the moment we haven't the zoom function.
You use my fork : [https://github.com/tanganellilore/visavail](https://github.com/tanganellilore/visavail)

I refresh this library with new features.

**Comment by Chatcola** [comment]
Thanks for replying.
Awesome, I'm new to JS and didn't see any exemples using this feature.

**Comment by tanganellilore** [comment]
See my editing......

**Comment by Chatcola** [comment]
More options and documentations. This is perfect !

Thanks a lot.
