### ISSUE TITLE
Upgrade to d3 v4/5

### ISSUE THREAD

**Issue by leqnam** [flrs/visavail#35]
Hi flrs,
Is there any work on this awsome project to upgrade to d3 v4 or 5?

**Comment by tanganellilore** [comment]
hi @leqnam ,

you can use my fork: [here](https://github.com/tanganellilore/visavail)

I enabling a series of enhancement and rework on this library. You can  use this, in the next month i think with @flrs we can merge my work with this repo but at the moment you can use my fork.

Good day

**Comment by tanganellilore** [comment]
Today we merged my fork with this project.

Now library is compatible with d3 v5 version

Please see how this library change!
