### ISSUE TITLE
Not able to integrate in  angular 6+

### ISSUE THREAD

**Issue by jayeshdhage07** [flrs/visavail#39]
I tried to integrate time data availability chart in angular 6+ , by installing D3, but not able to do that,
also i didn't get any example about how can i integrate time data availability chart [](http://phatduino.com.w010a51b.kasserver.com/visavail/example.htm) .

**Comment by tanganellilore** [comment]
Hi @amjayesh07,

I replicate Angular 6+ integration [here](https://codesandbox.io/s/angular-o8gxt).

Remember to add CSS file of visavail and add d3/moment dependecies in your package.json.

In next weeks i try to add a chapter into README file to explain how integrate into angular 2+.
Tell me if all is fine.

**Comment by jayeshdhage07** [comment]
Hey @tanganellilore , thanks man 🤘.

**Comment by tanganellilore** [comment]
Added documentation on new release
