### ISSUE TITLE
When pagination is enabled the time gaps is failing...

### ISSUE THREAD

**Issue by ghost** [flrs/visavail#4]
First of all thanks for the awesome extension.

Where there is an issue when pagination is enabled.

My guess is the issue lies in the following code: (please notice my comment in the code)

```
       if (maxDisplayDatasets > 0) {
        startSet = curDisplayFirstDataset;
        if (curDisplayFirstDataset + maxDisplayDatasets > dataset.length) {
          endSet = dataset.length;
        } else {
          endSet = curDisplayFirstDataset + maxDisplayDatasets;
        }
        maxPages = Math.ceil(dataset.length / maxDisplayDatasets); // especially this line of code. if maxPages is 0 there is time gaps (see image 1) when maxPages is not 0 then time gaps are all combined together (see image 2)
      } else {
        startSet = 0;
        endSet = dataset.length;
      }
```

**Image 1:**
![image](https://cloud.githubusercontent.com/assets/875754/18221154/aa0ebe2e-7147-11e6-81dc-e15c9a0d5f59.png)

**Image 2:**
![image](https://cloud.githubusercontent.com/assets/875754/18221180/e1049e08-7147-11e6-8b16-a8baf7db0aa0.png)

Any help is greatly appreciated!

Thanks again!

**Comment by flrs** [comment]
Thanks @peplamb for your feedback and for spotting this bug! I just fixed it in the most recent commit marked above. Please let me know if this solution fits your needs.

**Comment by ghost** [comment]
That was quick @flrs thank you!!!

One more minor issue:
the data says "from August 2016 to August 2016"
I am expecting to see: "from 8/30/2016 11:30:00 AM to 8/30/2016 1:45:00 PM"

For Example: when i set 
`var maxDisplayDatasets = 0;`
I get:
"from 8/30/2016 11:30:00 AM to 8/30/2016 1:45:00 PM"
and when i set:
`var maxDisplayDatasets = 5; // for example`
I get:
"from August 2016 to August 2016"

Thanks again!

**Comment by flrs** [comment]
@peplamb, I just added a fix. Let me know if that works!

**Comment by ghost** [comment]
Works great!  Thank you flrs!
