### ISSUE TITLE
Spacing between title and its bar

### ISSUE THREAD

**Issue by ijunaid8989** [flrs/visavail#44]
![image](https://user-images.githubusercontent.com/13561999/78868102-ba093680-7a5b-11ea-9872-5dee38a2cc81.png)

Is there any way to give space between the title and its consecutive bar?..

I have looked the docs but I am unable to find any option for this. my titles are long and they are going down in the bars.

**Comment by tanganellilore** [comment]
Hi,

you can enlarge the space between title and bar with the combination of margin and padding, like:

`
margin:{left:180}, 
padding:{left:-180}
`

Please close the issue if you resolve it.

**Comment by ijunaid8989** [comment]
yes thanks it worked, just one last question:

![image](https://user-images.githubusercontent.com/13561999/78878632-21c77d80-7a6c-11ea-8a13-18ba1b6261b9.png)

is there any property available for the very left margin? for the title?

**Comment by ijunaid8989** [comment]
got it thanks
