### ISSUE TITLE
Add text/html inside Bar

### ISSUE THREAD

**Issue by potapovnikita** [flrs/visavail#47]
How i can add text/html inside the bar?

For example: 
![Снимок экрана 2021-01-26 в 21 53 18](https://user-images.githubusercontent.com/20072877/105890871-f3c62080-6020-11eb-9098-100f03d892b3.png)

Thanks!

**Comment by tanganellilore** [comment]
In this moment is not possible do it

**Comment by tanganellilore** [comment]
Before develop it, can you explain what you thing what is needed to add on the bar?
Thanks @potapovnikita

**Comment by potapovnikita** [comment]
I think that we should be able to add any html node.

**Comment by tanganellilore** [comment]
Sorry, but if you use visavail, that is based on d3 library, you know that inside svg graph, html tag is supported by IE.

`foreignObject` that is used on svg for add div or something similar, is not supported by IE.

**Comment by tanganellilore** [comment]
`foreignobject` that is used on svg for add `div` or something similar, is supporter only in certain browser, and not in IE 11.
