### ISSUE TITLE
Don't use in typescript

### ISSUE THREAD

**Issue by daichisakurai** [flrs/visavail#52]
Is there .d.ts file?
I would like you to make .d.ts file and upload npm

**Comment by tanganellilore** [comment]
Sorry,
Can you explain better your point?
Visavail is already on npm and can be used on react/angular with webpack and typescript.

**Comment by daichisakurai** [comment]
* code
```
import * as visavail from "visavail";
```

* error
```
Could not find a declaration file for module 'visavail'. 'C:/Users/workspace/project/node_modules/visavail/visavail.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/visavail` if it exists or add a new declaration (.d.ts) file containing `declare module 'visavail';`ts(7016)
```

**Comment by tanganellilore** [comment]
There is AN issue on your side, probably related to your react/webpack configuration.

Check the read e file, there are 2 examples dedicated to react and angular, with a real demo with a real application. 

Remember on webpack that you need to declare library an so on for compiler. 
I maintain the issue opened for 5 days, after i will close.
