### ISSUE TITLE
Cannot update title

### ISSUE THREAD

**Issue by tsulatsitamim** [flrs/visavail#56]
Hi, thanks for this library, i can make downtime graph easily with this library.

I try to update existing chart by passing new options contain new title on `updateGraph` method, but the title doesn't change.

I try to console log the parameter on  `updateGraph` method it show the old options, event if I pass object with title key only 
![2021-08-26_18-52_1](https://user-images.githubusercontent.com/5946791/130958140-0a556b2b-c262-49ef-9bfa-15b5200a4d57.png)

thank you

**Comment by tanganellilore** [comment]
Please,
check you code, probably you passed a wrong options.
You need to pass all json options, not only one keyword.

Standard code work perfectly with updateGraph and updateOptions, check it:
https://codesandbox.io/s/flamboyant-cdn-44mnl
