### ISSUE TITLE
Non-binary states

### ISSUE THREAD

**Issue by delaaxe** [flrs/visavail#8]
Hi,

Thanks for making this available, I've been looking for a long time for such a lib!

I'd like to display an arbitrary number of states through the timeline, not just data/no data. Ideally with assignable labels and colors.

This would certainly be useful for others and would make the library more generic.

Let me know if this is something you would consider.

Best,
Axel

**Comment by flrs** [comment]
Hey @delaaxe!

Thank you for this nice suggestion. It seems as if this library more and more transforms into a general Gantt library, with all the bells and whistles. Your request certainly points into that direction, and I am happy that you can use Visavail.js for your purposes!

Thank you so much for figuring out yourself which changes to make to implement your feature. I have reviewed your code and changed a few minor details. Your custom category code was merged in commit c59cb69623aef475f59a9638c22d87a33747b588.

Keep us updated about where you are using the new feature!

Thanks,
Florian

**Comment by delaaxe** [comment]
Thanks for your feedback !

In case you're wondering, I used your library in order to display instant-messaging statuses over time (Active/Away/In a meeting etc). It was easy to adapt.
